test:
    image: golang:1.22
    script:
        - "go test ./..."

build-push-image:
    image: docker:25.0.5
    rules:
        - if: $CI_COMMIT_BRANCH == "master"
    script:
        - 'docker buildx build -t "$CI_REGISTRY:$CI_REGISTRY_IMAGE" -f ./Dockerfile.multistage .'
        - 'docker login -u "$CI_REGISTRY_USER" -p $CI_REGISTRY_PASSWORD" "$CI_REGISTRY"'
        - 'docker push "$CI_REGISTRY:$CI_REGISTRY_IMAGE"'