# yaml-language-server: $schema=https://gitlab.com/gitlab-org/gitlab/-/raw/master/app/assets/javascripts/editor/schema/ci.json
stages:
  - testing
  - build-push-image

test:
  stage: testing
  image: golang:1.22
  variables:
    SKIP_DB_TEST: "true"
  script:
    - "go test ./internal"

build-push-image:
  stage: build-push-image
  image: docker:25.0.5
  services:
    - docker:25.0.5-dind
  rules:
    - if: $CI_COMMIT_BRANCH == "master" && $CI_COMMIT_TAG == "stable"
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE
  script:
    - 'docker buildx build -t "$IMAGE_TAG" -f ./Dockerfile.multistage .'
    - 'docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"'
    - 'docker push "$IMAGE_TAG"'
