stages:
    - testing
    - build-push-image

test:
    stage: testing
    image: golang:1.22
    script:
        - "go test ./internal"

build-push-image:
    stage: build-push-image
    image: docker:25.0.5
    services:
        - docker:25.0.5-dind
    rules:
        - if: $CI_COMMIT_BRANCH == "master"
        - if: $CI_COMMIT_TAG == "stable"
    variables:
        IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    script:
        - 'docker buildx build -t "$IMAGE_TAG" -f ./Dockerfile.multistage .'
        - 'docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"'
        - 'docker push "$IMAGE_TAG"'