// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Port struct {
	ServiceName             *string `json:"serviceName,omitempty"`
	PortNumber              []int   `json:"portNumber"`
	TransportProtocol       *string `json:"transportProtocol,omitempty"`
	Description             *string `json:"description,omitempty"`
	Assignee                *string `json:"assignee,omitempty"`
	Contact                 *string `json:"contact,omitempty"`
	RegistrationDate        *string `json:"registrationDate,omitempty"`
	ModificationDate        *string `json:"modificationDate,omitempty"`
	Reference               *string `json:"reference,omitempty"`
	ServiceCode             *string `json:"serviceCode,omitempty"`
	UnauthorizedUseReported *string `json:"unauthorizedUseReported,omitempty"`
	AssignmentNotes         *string `json:"assignmentNotes,omitempty"`
}

type Query struct {
}
